New features, fixes and coverage (#1)
Additions

Say hi to reduce, filter, map, finally, fail and lastly.
Methods reduce, filter and map does exactly what the Array methods do.
Methods fail and lastly are for js environments that does not support keywords as names. fail is catch and lastly is finally.
Fixes & Improvements

Failing listeners does not reject the promise.
Methods all and race now correctly resolves when iterable is empty.
Method promisify has gotten a little overhaul.
Method flow more correctly checks for crafted array objects.
Method delay no longer resolves when the promise is rejected.
In method flow yield an array or a generator for a shortcut to method all.
Now handling one deferred handler instead of an array of one handler.
Method onNotify throws a TypeError if the handler is not a function
Miscellaneous

100% coverage of tests.
New coverage badge :P
Method progress renamed to onNotify.
Moved browser release to separate file.
Bumped the version